version: "3"

services:
  ##ref: https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/README.md
  openvpn:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    container_name: openvpn
    ports:
      - "443:443/tcp"
      - "1194:1194/udp"
    volumes:
      - /out:/out
      - ./bin:/usr/local/bin

    # environment:
    restart: always
    command: ["ovpn_run.sh"]
