version: "3"

services:
  ##ref: https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/README.md
  openvpn:
    build: .
    cap_add:
      - NET_ADMIN
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - /out:/out
    environment:
      - HOST_IP=${HOST_IP}
    restart: always
    command: ["openvpn", "--config", "/etc/openvpn/server.conf"]